name: gearsh_app
description: "Gearsh - The Global Marketplace to Book DJs, Photographers, Videographers & Creative Talent Worldwide"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies: 
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.1
  google_fonts: ^6.0.0
  cached_network_image: ^3.3.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.6
  http: ^1.6.0
  shared_preferences: ^2.5.4
  flex_color_scheme: ^8.2.0
  flutter_animate: ^4.3.0
  google_maps_flutter: ^2.4.0
  table_calendar: ^3.0.9
  fl_chart: ^1.1.1
  geocoding: ^4.0.0
  fuzzywuzzy: ^1.2.0
  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  firebase_crashlytics: ^4.0.1
  firebase_analytics: ^11.0.1
  # Social Sign-In
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.4
  # Utilities
  crypto: ^3.0.6
  url_launcher: ^6.2.1
  package_info_plus: ^8.0.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6 
  freezed: ^3.0.6 
  json_serializable: ^6.7.1 
  flutter_launcher_icons: ^0.14.1

  flutter_lints: ^6.0.0

# App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/gearsh_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#020617"
  adaptive_icon_foreground: "assets/images/gearsh_logo.png"
  web:
    generate: true
    image_path: "assets/images/gearsh_logo.png"
  windows:
    generate: true
    image_path: "assets/images/gearsh_logo.png"


flutter:

  uses-material-design: true
  assets:
    - assets/images/gearsh_logo.png
    - assets/images/storyboard.png
    - assets/images/storyboard2.png
    - assets/images/allthestars.jpg
    - assets/images/icons/calendar.png
    - assets/images/icons/art.png
    - assets/images/icons/superstar.png
    - assets/images/artists/
    - assets/images/artists/rixelton.jpg
    - assets/images/artists/dripmaker.png
